services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: my_flask_backend
    image: ladybug-backend:latest
    ports:
      - "5000:5000"
    env_file:
      - backend/.env
    restart: always
    environment:
      - NODE_URL=http://probot:3000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  probot:
    build:
      context: .
      dockerfile: Dockerfile.probot
    container_name: my_probot_app
    image: ladybug-probot:latest
    ports:
      - "3000:3000"
    env_file:
      - probot/.env
    environment:
      - API_URL=http://backend:5000
