FROM python:3.12-slim
# Set the working directory in the container
WORKDIR /usr/src/app
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN apt-get -y update
RUN apt-get -y install git
RUN python -c "import nltk; nltk.download('averaged_perceptron_tagger_eng'); nltk.download('wordnet')"
COPY backend/ .
EXPOSE 5000
CMD [ "python", "index.py" ]
