FROM python:3.12-slim
# Set the working directory in the container
WORKDIR /usr/src/app
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN apt-get update && apt-get install -y git
COPY backend/ .
EXPOSE 5000
CMD [ "python", "index.py" ]
